### PR TITLE
chore: add dependabot and codeql

### PR DESCRIPTION
**Pull request by Keritial**

### CODE REVIEW

**Comment by Keritial** [comment]
Is CodeQL needed to spilt into a separated file?

**Comment by TheNightmareX** [comment]
thanks! but maybe we should remove the instruction comments? we may keep some links of these instructions though like line 4 in [dependabot.yml](https://github.com/Cridium/cridium-server/pull/40/files#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28).

**Review by Char2sGu — CHANGES_REQUESTED** [review]
thanks! but maybe we should remove the instruction comments? we may keep some links of these instructions though like line 4 in [dependabot.yml](https://github.com/Cridium/cridium-server/pull/40/files#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28).

**Comment by Char2sGu** [comment]
hi i've done some modifications on `workflow.yml`, is it ok with you?

**Comment by Keritial** [comment]
it should be OK

**Pull request merged**
